### ISSUE TITLE
How do I install this without composer?

### ISSUE THREAD

**Issue by AndreyNazarchuk** [thephpleague/oauth2-google#23]
How do I install this without composer properly so I can use PHPMailer's get_oauth_token.php properly?

**Comment by shadowhand** [comment]
We don't support non-composer installation.

**Comment by AndreyNazarchuk** [comment]
Well I am using Godaddy hosting which requries jumping over mountains to get root access.

**Comment by AndreyNazarchuk** [comment]
@shadowhand please?

**Comment by shadowhand** [comment]
Why would you need root access to install with composer? Just use composer locally and then FTP or whatever you have to do to upload files to GoDaddy.

**Comment by AndreyNazarchuk** [comment]
I cant even ssh into it properly

**Comment by shadowhand** [comment]
If you can install locally you can upload your files by whatever means available. Composer is the ~~preferred~~ standard way to install PHP packages these days.

**Comment by AndreyNazarchuk** [comment]
I know, but no matter what folder I put oauth2 into I still get an class not found error when running get_oauth2_token.php

**Comment by shadowhand** [comment]
You probably need an autoloader.

**Comment by AndreyNazarchuk** [comment]
...how?

**Comment by shadowhand** [comment]
http://lmgtfy.com/?q=php+autoloader

**Comment by shadowhand** [comment]
Composer comes with an autoloader. Upload it with all your other project files. I don't see what the problem is.

**Comment by AndreyNazarchuk** [comment]
Thank you for your time and patience, found out how to use composer with GoDaddy.

**Comment by lilliesAndRoses** [comment]
@AndreyNazarchuk  Can you please mention what have you found? I also need to know how to user composer with GoDaddy

**Comment by gmariani** [comment]
shadowhand, let me correct that for you:

"Composer is the ~~preferred~~ ~~standard~~ cool way to install PHP packages these days."

Composer is overkill. I shouldn't have to install a program, configure software just to copy and paste a handful of files to the server. It's asinine.

**Comment by shadowhand** [comment]
I don't know what to tell you. Composer is a single file that automates dependency resolution and provides better security than "copy and pasting ... the the server". Best of luck using techniques from 2004.

**Comment by gmariani** [comment]
Exactly the answer i would expect from someone who feels their way is the only correct way.

**Comment by shadowhand** [comment]
Every major framework and the PHP community as a whole has largely embraced composer. It makes things better for all of us. I feel like you are willfully choosing to make things worse for yourself by refusing to learn a new (and better) way to do things. Composer has been with us for over 5 years now and has improved life for many of us.

In the end, it's up to you.

**Comment by ultrageoff** [comment]
I signed up to Github again (left it for Mercurial, having seen people waste hours trying to do just to do the most straightforward things with Git and/or needing to rescue their projects from a Git nightmare) - just to agree with gmariani. Including some classes should be a 30 second job, max. With composer, you too can spend much longer doing a starightforward thing and then have yourself one of those muliple-dependency web apps that breaks every time there's an update anywhere on planet Earth. And takes forever to - phew - load a name and address!!!!!! Most frameworks disappeared up their own butts many years ago. I'll be using a previous version of PHP mailer to do exactly the same thing I'd now need to learn Composer for.

**Comment by ramsey** [comment]
Here are a few steps that should get you up-and-running with league/oauth2-google library:

1. Download Composer to your project root directory. It'll just be `composer.phar`. You don't need to move it anywhere else. https://getcomposer.org/download/
2. From your project root, run `php composer.phar require league/oauth2-google --prefer-dist`. This will create a `vendor/` directory and download some files into it. It will also create `composer.json` and `composer.lock` files in your project root.
3. Use Composer's autoloader in your project by including this line in your project's header files or bootstrap files or pre-loader files (whatever you want to call them, this line should go before anything is loaded). Modify the path according to your needs.

    ``` php
    require __DIR__ . '/vendor/autoload.php';
    ```

4. At this point, you no longer need to use Composer, if you don't want to. Simply remove the `composer.phar` file and be sure to commit everything in the `vendor/` directory as part of your project. You can also remove the `composer.json` and `composer.lock` files, but I recommend keeping them with your project just in case you ever want to go back to using Composer.

This is how you get all the source code and dependencies for league/oauth2-google installed into your project in a quick and seamless way, without relying too much on Composer for all your other project code. Since we have dependencies on other Composer packages, this is necessary, but once you've downloaded things to the `vendor/` directory and have including the autoloader in your project, there's no need to continue using Composer; you've essentially just used it as a downloader, and that's fine.

I'm locking this thread, since further complaints about Composer are not beneficial to this project.
